"""creo tablas para entrada-comentario-categoria

Revision ID: 0077f52f3849
Revises: d94fc1d62b47
Create Date: 2023-08-02 19:26:08.341392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0077f52f3849'
down_revision = 'd94fc1d62b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('contenido', sa.String(length=140), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('autor', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['etiqueta'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=140), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('autor', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['etiqueta'], ['entrada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('entrada')
    op.drop_table('categoria')
    # ### end Alembic commands ###
